### ISSUE TITLE
why the initial value of binarizer threshold is 5e-3.

### ISSUE THREAD

**Issue by Breezeqiuyu** [arunmallya/piggyback18#3]
Hello, thank you very much for sharing the code on GitHub. But I have a question and hope to get your answer. In your paper, mention "We initialized the real-valued weights with a value of 1e-2 with a binarizer threshold (τ, in Equation 4) of 5e-3 in All our experiments", I don't understand why the initial value of binarizer threshold is 5e-3. Will this value change during the training according to the data set? Is it fixed? I don't know the origin of this value. Your paper doesn't mention why it is 5e-3, so I want to consult you, I hope to get your reply, thank you very much, I wish you a happy life.

**Comment by Breezeqiuyu** [comment]
@arunmallya

**Comment by arunmallya** [comment]
It's just a value we found using cross-validation. You can use a different value if you like.
Different thresholds will result in a different value of sparsity and accuracy. 
The values we have used might not be the most optimal ones.

**Comment by Breezeqiuyu** [comment]
> It's just a value we found using cross-validation. You can use a different value if you like.
> Different thresholds will result in a different value of sparsity and accuracy.
> The values we have used might not be the most optimal ones.

I'm so glad to see your reply. This question has troubled me for a long time. So is this a value that you have tested through a lot of experiments? Not based on theory. I would also like to ask, is your method applicable to other CNN? Thank you for your reply.

**Comment by Breezeqiuyu** [comment]
@arunmallya

**Comment by arunmallya** [comment]
The paper has results on multiple CNNs including VGG, ResNet, and DenseNet. So to answer your question, yes, the method is applicable to other CNNs.

**Comment by Breezeqiuyu** [comment]
> The paper has results on multiple CNNs including VGG, ResNet, and DenseNet. So to answer your question, yes, the method is applicable to other CNNs.



Thank you very much. Your reply is very helpful to me.
